// 最新 GAS Web App 部署網址
const GAS_API_URL = "https://script.google.com/macros/s/AKfycbxXq7FITulvsma6lFhxk5u2Xut6_5dtfbEtZnxqjUkttYewEColE16scxcDR7tMJGEHHA/exec";
const SHEET_ID = '1L2W695-pGvilvh6JMyYaJwxhm4QOpFxUG-VQUoFdCOQ';
const ADMIN_PASSWORD = "7Jesus40";

const today = new Date();
today.setHours(0, 0, 0, 0);
const currentYear = today.getFullYear();

let allEvents = [];
let currentCategory = '全部';
let isAdmin = false;
let isEditingMode = false;
let uploadedImageFile = null;

// DOM 元素
const container = document.getElementById('event-container');
const categoryFilter = document.getElementById('category-filter');
const topDynamicBtn = document.getElementById('topDynamicBtn');
const topBtnIcon = document.getElementById('topBtnIcon');
const topBtnLabel = document.getElementById('topBtnLabel');
const logoutBtn = document.getElementById('logoutBtn');

const eventModalEl = document.getElementById('eventModal');
const eventModal = new bootstrap.Modal(eventModalEl);
const eventForm = document.getElementById('eventForm');
const submitBtn = document.getElementById('submitBtn');
const modalTitle = document.getElementById('modalTitle');

// 日期相關元素
const formDeadlineDate = document.getElementById('formDeadlineDate');
const formEventStart = document.getElementById('formEventStart');
const formEventEnd = document.getElementById('formEventEnd');
const formDisplayDate = document.getElementById('formDisplayDate');

const dropImage = document.getElementById('drop_image');
const fileImageInput = document.getElementById('file_image');
const imagePreview = document.getElementById('imagePreview');
const imageFileName = document.getElementById('imageFileName');

const weekDays = ['日', '一', '二', '三', '四', '五', '六'];

// 自動由選取的日曆產生標準格式：08/17（一）～ 08/21（五）
function autoGenerateDisplayDate() {
  const startVal = formEventStart.value;
  const endVal = formEventEnd.value;
  if (!startVal) return;

  const startDate = new Date(startVal);
  const sMonth = String(startDate.getMonth() + 1).padStart(2, '0');
  const sDay = String(startDate.getDate()).padStart(2, '0');
  const sWeek = weekDays[startDate.getDay()];

  if (endVal) {
    const endDate = new Date(endVal);
    const eMonth = String(endDate.getMonth() + 1).padStart(2, '0');
    const eDay = String(endDate.getDate()).padStart(2, '0');
    const eWeek = weekDays[endDate.getDay()];
    // 波浪號前後帶標準空格
    formDisplayDate.value = `${sMonth}/${sDay}（${sWeek}）～ ${eMonth}/${eDay}（${eWeek}）`;
  } else {
    formDisplayDate.value = `${sMonth}/${sDay}（${sWeek}）`;
  }
}

formEventStart.addEventListener('change', () => {
  if (!formDeadlineDate.value) {
    formDeadlineDate.value = formEventStart.value;
  }
  autoGenerateDisplayDate();
});
formEventEnd.addEventListener('change', autoGenerateDisplayDate);

// 浮動微通知 Toast
function showToast(message) {
  let toast = document.getElementById("sysToast");
  if (!toast) {
    toast = document.createElement("div");
    toast.id = "sysToast";
    toast.className = "toast-notification";
    document.body.appendChild(toast);
  }
  toast.innerHTML = `<i class="bi bi-check-circle-fill text-success"></i> <span>${message}</span>`;
  toast.classList.add("show");
  setTimeout(() => {
    toast.classList.remove("show");
  }, 2200);
}

// 輔助函式：Google 雲端硬碟連結轉換為直接顯示的高畫質網址
function convertDriveUrl(url) {
  if (!url || url.trim() === '') return 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800';
  if (url.includes('drive.google.com')) {
    const match = url.match(/\/d\/([a-zA-Z0-9_-]+)/) || url.match(/id=([a-zA-Z0-9_-]+)/);
    if (match && match[1]) {
      return `https://drive.google.com/thumbnail?sz=w1280&id=${match[1]}`;
    }
  }
  return url;
}

function updateTopNavUI() {
  if (isAdmin) {
    document.body.classList.add("is-admin");
    topDynamicBtn.removeAttribute("href");
    topDynamicBtn.title = "發布新活動";
    topBtnLabel.textContent = "新增活動";
    topBtnIcon.className = "bi bi-plus-lg";
  } else {
    document.body.classList.remove("is-admin");
    topDynamicBtn.href = "https://www.kszionch.org.tw/";
    topDynamicBtn.title = "返回教會首頁";
    topBtnLabel.textContent = "回主頁";
    topBtnIcon.className = "bi bi-house-door";
  }
}

topDynamicBtn.addEventListener("click", (e) => {
  if (isAdmin) {
    e.preventDefault();
    openAddModal();
  }
});

logoutBtn.addEventListener("click", () => {
  isAdmin = false;
  sessionStorage.removeItem("is_event_admin");
  updateTopNavUI();
  renderEvents();
  showToast("已安全登出同工後台");
  if (window.location.search || window.location.hash) {
    window.history.replaceState({}, document.title, window.location.pathname);
  }
});

// 極簡暗號偵測：?a 或 #a 進入後台
const currentUrl = window.location.href.toLowerCase();
const hasAdminCode = currentUrl.includes("?a") || currentUrl.includes("#a");

if (sessionStorage.getItem("is_event_admin") === "true") {
  isAdmin = true;
  updateTopNavUI();
} else if (hasAdminCode) {
  setTimeout(() => {
    const pwd = prompt("請輸入同工管理密碼：");
    if (pwd === ADMIN_PASSWORD) {
      isAdmin = true;
      sessionStorage.setItem("is_event_admin", "true");
      updateTopNavUI();
      renderEvents();
      cleanExpiredEventsInSheet();
      showToast("已進入管理模式，右上角已解鎖「新增活動」");
    } else if (pwd !== null) {
      alert("密碼不正確！");
    }
  }, 200);
}

// 鍵盤快捷鍵：Ctrl + Alt + A 叫出登入
window.addEventListener("keydown", (e) => {
  if (e.ctrlKey && e.altKey && (e.key === "a" || e.key === "A")) {
    if (!isAdmin) {
      const pwd = prompt("請輸入同工管理密碼：");
      if (pwd === ADMIN_PASSWORD) {
        isAdmin = true;
        sessionStorage.setItem("is_event_admin", "true");
        updateTopNavUI();
        renderEvents();
        cleanExpiredEventsInSheet();
        showToast("已進入管理模式");
      }
    }
  }
});

// 圖片拖曳上傳綁定
dropImage.addEventListener("click", () => fileImageInput.click());
dropImage.addEventListener("dragover", (e) => { e.preventDefault(); dropImage.classList.add("dragover"); });
dropImage.addEventListener("dragleave", () => dropImage.classList.remove("dragover"));
dropImage.addEventListener("drop", (e) => {
  e.preventDefault();
  dropImage.classList.remove("dragover");
  if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
    handleImageSelect(e.dataTransfer.files[0]);
  }
});
fileImageInput.addEventListener("change", (e) => {
  if (e.target.files && e.target.files.length > 0) {
    handleImageSelect(e.target.files[0]);
  }
});

function handleImageSelect(file) {
  uploadedImageFile = file;
  imageFileName.textContent = `✓ 已選取：${file.name}`;
  const reader = new FileReader();
  reader.onload = (e) => {
    imagePreview.src = e.target.result;
    imagePreview.style.display = "block";
  };
  reader.readAsDataURL(file);
}

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result.split(",")[1]);
    reader.onerror = error => reject(error);
    reader.readAsDataURL(file);
  });
}

function openAddModal() {
  isEditingMode = false;
  modalTitle.textContent = "發布新活動";
  submitBtn.textContent = "發布並同步至雲端";
  eventForm.reset();
  uploadedImageFile = null;
  imagePreview.src = "";
  imagePreview.style.display = "none";
  imageFileName.textContent = "";

  document.getElementById("editRowIndex").value = "";
  document.getElementById("editOldTitle").value = "";
  document.getElementById("existingImageUrl").value = "";

  formDeadlineDate.value = new Date().toISOString().split("T")[0];
  formEventStart.value = "";
  formEventEnd.value = "";
  formDisplayDate.value = "";

  eventModal.show();
}

function startEdit(item) {
  isEditingMode = true;
  modalTitle.textContent = "編輯活動內容";
  submitBtn.textContent = "儲存修改並更新雲端";
  uploadedImageFile = null;
  eventForm.reset();

  document.getElementById("editRowIndex").value = item._rowIndex || "";
  document.getElementById("editOldTitle").value = item.title || "";
  document.getElementById("existingImageUrl").value = item.image || "";

  document.getElementById("formTitle").value = item.title || "";
  document.getElementById("formCategory").value = item.category || "";
  document.getElementById("formStatus").value = item.status || "報名中";
  document.getElementById("formLink").value = item.link || "";
  document.getElementById("formDisplayDate").value = item.displayDate || "";

  const parsed = parseEventDate(item.date);
  if (!isNaN(parsed.getTime())) {
    const y = parsed.getFullYear();
    const m = String(parsed.getMonth() + 1).padStart(2, '0');
    const d = String(parsed.getDate()).padStart(2, '0');
    formDeadlineDate.value = `${y}-${m}-${d}`;
  } else {
    formDeadlineDate.value = "";
  }

  formEventStart.value = "";
  formEventEnd.value = "";

  if (item.image) {
    imageFileName.textContent = "(保留原海報圖片)";
    imagePreview.src = convertDriveUrl(item.image);
    imagePreview.style.display = "block";
  } else {
    imagePreview.src = "";
    imagePreview.style.display = "none";
    imageFileName.textContent = "";
  }

  eventModal.show();
}

async function startDelete(item) {
  const confirmDelete = confirm(`確定要永久刪除活動「${item.title}」嗎？\n此動作將同步從 Google 試算表中移除。`);
  if (!confirmDelete) return;

  try {
    await fetch(GAS_API_URL, {
      method: "POST",
      mode: "cors",
      headers: { "Content-Type": "text/plain;charset=utf-8" },
      body: JSON.stringify({
        action: "delete",
        rowIndex: item._rowIndex
      })
    });

    showToast("✓ 活動已成功刪除！");
    setTimeout(loadEventsFromSheet, 1000);
  } catch (err) {
    console.error("刪除失敗：", err);
    alert("刪除失敗，請檢查網路連線。");
  }
}

// 表單提交（具備 CORS 跨域安全與非必填分類支援）
eventForm.addEventListener("submit", async (e) => {
  e.preventDefault();
  submitBtn.disabled = true;
  submitBtn.textContent = "資料同步處理中，請稍候...";

  try {
    const dVal = formDeadlineDate.value;
    const dateObj = new Date(dVal);
    const m = String(dateObj.getMonth() + 1).padStart(2, '0');
    const d = String(dateObj.getDate()).padStart(2, '0');
    const formattedDate = `${m}/${d}`;

    const payload = {
      action: isEditingMode ? "edit" : "create",
      rowIndex: document.getElementById("editRowIndex").value ? parseInt(document.getElementById("editRowIndex").value) : null,
      old_title: document.getElementById("editOldTitle").value,
      title: document.getElementById("formTitle").value.trim(),
      date: formattedDate,
      displayDate: document.getElementById("formDisplayDate").value.trim(),
      category: document.getElementById("formCategory").value.trim(),
      status: document.getElementById("formStatus").value.trim(),
      link: document.getElementById("formLink").value.trim(),
      image: document.getElementById("existingImageUrl").value
    };

    if (uploadedImageFile) {
      const b64 = await fileToBase64(uploadedImageFile);
      payload.file_image = {
        name: uploadedImageFile.name,
        type: uploadedImageFile.type,
        data: b64
      };
    }

    const res = await fetch(GAS_API_URL, {
      method: "POST",
      mode: "cors",
      redirect: "follow",
      headers: { "Content-Type": "text/plain;charset=utf-8" },
      body: JSON.stringify(payload)
    });

    const result = await res.json();
    if (result.result === "error") {
      alert("儲存失敗：" + result.message);
      return;
    }

    eventModal.hide();
    eventForm.reset();
    showToast(isEditingMode ? "修改成功！雲端已同步更新" : "發布成功！已新增至活動列表");

    setTimeout(loadEventsFromSheet, 1200);
  } catch (err) {
    console.error("處理失敗：", err);
    alert("連線時發生異常：" + err.message + "\n請確認試算表 Apps Script 部署版本中「誰可以存取」已設為「所有人」。");
  } finally {
    submitBtn.disabled = false;
    submitBtn.textContent = isEditingMode ? "儲存修改並更新雲端" : "發布並同步至雲端";
  }
});

// 日期解析輔助函式
function parseEventDate(dateStr) {
  if (!dateStr) return new Date(0);
  const clean = dateStr.trim();
  if (clean.includes('-') || clean.split('/').length === 3) {
    return new Date(clean.replace(/-/g, '/'));
  }
  return new Date(`${currentYear}/${clean}`);
}

// 渲染畫面的主函式
function renderEvents() {
  const filteredEvents = allEvents
    .filter(event => {
      const eventDate = parseEventDate(event.date);
      const isNotExpired = !isNaN(eventDate.getTime()) && (eventDate.setHours(23, 59, 59, 999) >= today.getTime());
      
      let matchesCategory = false;
      if (currentCategory === '全部') {
        matchesCategory = true;
      } else {
        matchesCategory = (event.category === currentCategory);
      }

      return isNotExpired && matchesCategory;
    })
    .sort((a, b) => {
      const dateA = parseEventDate(a.date);
      const dateB = parseEventDate(b.date);
      return dateA - dateB;
    });

  if (filteredEvents.length === 0) {
    container.innerHTML = `<div class="col-12 text-muted py-5 text-center fs-5">目前這個分類沒有進行中的活動</div>`;
    return;
  }

  container.innerHTML = filteredEvents.map((event, index) => {
    let badgeClass = 'bg-light text-dark border';
    if (event.status === '報名中' || event.status === '訂便當') badgeClass = 'bg-dark text-white';

    const imageUrl = convertDriveUrl(event.image);

    return `
    <div class="col-md-4">
      <div class="card h-100 border-0 shadow-sm rounded-4 overflow-hidden transition-hover bg-white position-relative">
        
        <!-- 管理員專屬：編輯與刪除小按鈕 -->
        <div class="admin-card-actions">
          <button class="btn-action-pill btn-edit" data-idx="${index}">✏️ 編輯</button>
          <button class="btn-action-pill btn-action-delete btn-delete" data-idx="${index}">🗑️ 刪除</button>
        </div>

        <img src="${imageUrl}" class="card-img-top card-cover-img" alt="${event.title}">
        <div class="card-body p-4 d-flex flex-column">
          <div class="mb-2">
            <span class="text-muted fw-semibold small">
              <i class="bi bi-calendar3 me-1"></i> ${event.displayDate}
            </span>
          </div>
          
          <h5 class="fw-bold mb-3">${event.title}</h5>
          
          <div class="mt-auto d-flex justify-content-between align-items-center">
            <span class="badge ${badgeClass} px-2 py-1 rounded-pill">${event.status}</span>
            <a href="${event.link}" target="_blank" class="text-dark text-decoration-none fw-bold small">
              立即報名 <i class="bi bi-arrow-right-short fs-5 align-middle"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    `;
  }).join('');

  container.querySelectorAll('.btn-edit').forEach((btn, idx) => {
    btn.addEventListener('click', () => startEdit(filteredEvents[idx]));
  });
  container.querySelectorAll('.btn-delete').forEach((btn, idx) => {
    btn.addEventListener('click', () => startDelete(filteredEvents[idx]));
  });
}

// 自動檢查並從 Google 試算表刪除過期活動
async function cleanExpiredEventsInSheet() {
  if (!isAdmin) return;

  const expiredItems = allEvents.filter(e => {
    const eDate = parseEventDate(e.date);
    return !isNaN(eDate.getTime()) && (eDate.setHours(23, 59, 59, 999) < today.getTime());
  }).sort((a, b) => b._rowIndex - a._rowIndex);

  if (expiredItems.length === 0) return;

  for (const item of expiredItems) {
    try {
      await fetch(GAS_API_URL, {
        method: "POST",
        mode: "cors",
        headers: { "Content-Type": "text/plain;charset=utf-8" },
        body: JSON.stringify({
          action: "delete",
          rowIndex: item._rowIndex
        })
      });
    } catch (err) {
      console.error("自動清理失敗：", err);
    }
  }

  showToast(`已自動清理 ${expiredItems.length} 筆過期活動！`);
  setTimeout(loadEventsFromSheet, 1000);
}

// 動態更新分類標籤按鈕
function syncCategoryButtons() {
  const categories = new Set(['全部']);
  allEvents.forEach(e => {
    if (e.category && e.category.trim()) categories.add(e.category.trim());
  });

  categoryFilter.innerHTML = '';
  categories.forEach(cat => {
    const btn = document.createElement('button');
    btn.className = `btn rounded-pill px-4 py-2 fw-semibold ${cat === currentCategory ? 'btn-dark text-white shadow-sm' : 'btn-light text-muted'}`;
    btn.textContent = cat;
    btn.setAttribute('data-category', cat);
    btn.addEventListener('click', () => {
      currentCategory = cat;
      syncCategoryButtons();
      renderEvents();
    });
    categoryFilter.appendChild(btn);
  });
}

// 從 Google 試算表載入資料
async function loadEventsFromSheet() {
  try {
    const csvUrl = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&_t=${Date.now()}`;
    const response = await fetch(csvUrl);
    const csvText = await response.text();

    const lines = csvText.split('\n');
    allEvents = [];

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      const row = [];
      let match;
      const regex = /(?:,|\n|^)("(?:(?:"")*[^"]*)*"|[^",\n]*|(?:\n|$))/g;
      while ((match = regex.exec(line)) && match[0] !== "") {
        let val = match[1] || "";
        val = val.replace(/^"|"$/g, "").replace(/""/g, '"').trim();
        row.push(val);
      }

      if (row.length >= 7) {
        allEvents.push({
          _rowIndex: i + 1,
          date: row[0],
          displayDate: row[1],
          title: row[2],
          category: row[3],
          status: row[4],
          link: row[5],
          image: row[6]
        });
      }
    }

    syncCategoryButtons();
    renderEvents();

    if (isAdmin) {
      cleanExpiredEventsInSheet();
    }
  } catch (error) {
    console.error('讀取試算表失敗：', error);
    container.innerHTML = `<div class="col-12 text-danger py-4 text-center">無法載入活動資料，請確認試算表共用設定已開啟。</div>`;
  }
}

loadEventsFromSheet();